apiVersion: v1
kind: Secret
metadata:
  name: ghcr-registry-secret
  namespace: practical-work-3
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "c3ktcmV4OmdocF8yd0NwM2ZNeGRiclFCSWkxT1pNSVNWb1EzcXNwV1EzWk54amg="
        }
      }
    }
