apiVersion: v2
name: monitoring
description: Umbrella chart for Prometheus, Loki and Grafana
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: 62.7.0
    repository: https://prometheus-community.github.io/helm-charts
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts

