{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: {{ .Values.namespace.django }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
    app: postgres
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - {{ .Values.postgres.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
{{- end }}

