{{- if .Values.django.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  namespace: {{ .Values.namespace.django }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
    app: django-app
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  db_user: {{ .Values.secrets.db_user | b64enc }}
  db_password: {{ .Values.secrets.db_password | b64enc }}
  secret_key: {{ .Values.secrets.secret_key | b64enc }}
{{- end }}

