{{- if and .Values.monitoring.serviceMonitor.enabled .Values.django.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: django-service-monitor
  namespace: {{ .Values.namespace.django }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
    app: django-app
{{- with .Values.monitoring.serviceMonitor.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: django-app
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace.django }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}

